[manifest]
version = '1.0.0'
dump_lua = true
priority = 0

# Add info_queue bubbles if needed
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
match_indent = true
position = 'before'
pattern = '''
local cols
'''
payload = '''
if obj and obj.artist_credits and Ortalab.config.credit_pos == 2 then
    for _, artist in ipairs(obj.artist_credits) do
        info_boxes[#info_boxes+1] =
            {n=G.UIT.R, config={align = "cm"}, nodes={
                {n=G.UIT.R, config={align = "cm", colour = lighten(G.C.JOKER_GREY, 0.5), r = 0.1, padding = 0.05, emboss = 0.05}, nodes={
                    {n=G.UIT.R, config={align = "cm", colour = darken(G.ARGS.LOC_COLOURS[artist], 0.15), r = 0.1}, nodes={
                        {n=G.UIT.R, config={align = "tm", minh = 0.36, padding = 0.03}, nodes={
                            {n=G.UIT.T, config={text = localize('ortalab_artist'), scale = 0.32, colour = G.C.UI.TEXT_LIGHT}}
                        }},
                        {n=G.UIT.R, config={align = "cm", minw = 1.5, minh = 0.4, r = 0.1, padding = 0.05, colour = lighten(G.ARGS.LOC_COLOURS[artist], 0.5)}, nodes={
                            {n=G.UIT.R, config={align = "cm", padding = 0.03}, nodes={
                                {n=G.UIT.R, config = {align = 'tm'}, nodes = {
                                    {n=G.UIT.O, config={
                                        object = DynaText({string = localize{type = 'raw_descriptions', set = 'Ortalab Artist', key = artist},
                                        colours = {G.C.UI.TEXT_DARK},
                                        silent = true,
                                        pop_in = 0,
                                        pop_in_rate = 4,
                                        y_offset = -0.6,
                                        scale =  0.27
                                        })
                                    }}
                                }}
                            }}
                        }}
                    }}
                }}
            }}
    end
end

'''
