[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

## Chameleon tooltip
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''if add and not G.GAME.banned_keys[v.key] then'''
position = 'before'
match_indent = true
payload = '''if G.GAME.modifiers.ortalab_only and _type ~= 'Seal' then
    if not v.mod or v.mod.id ~= 'ortalab' then
        add = false
    end 
end
'''

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''local _, boss = pseudorandom_element(eligible_bosses, pseudoseed('boss'))'''
position = 'before'
match_indent = true
payload = '''if G.GAME.modifiers.ortalab_only then
    for k, v in pairs(eligible_bosses) do
        if eligible_bosses[k] and not G.P_BLINDS[k].mod or G.P_BLINDS[k].mod.id ~= 'ortalab' then
            eligible_bosses[k] = nil
        end
    end
end
'''

## Chameleon tooltip
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''if _pool_size == 0 then'''
position = 'before'
match_indent = true
payload = '''
if _pool_size == 0 then
    local new_pool = {}
    if G.GAME.modifiers.ortalab_only then
        local loteria_pool = get_current_pool('Loteria')
        local replacement_loteria = pseudorandom_element(loteria_pool, pseudoseed('ortalab_only'))
        while replacement_loteria == 'UNAVAILABLE' do
            replacement_loteria = pseudorandom_element(loteria_pool, pseudoseed('ortalab_only_resample'))
        end
        local zodiac_pool = get_current_pool('Zodiac')
        local replacement_zodiac = pseudorandom_element(zodiac_pool, pseudoseed('ortalab_only'))
        while replacement_zodiac == 'UNAVAILABLE' do
            replacement_zodiac = pseudorandom_element(zodiac_pool, pseudoseed('ortalab_only_resample'))
        end
        if SMODS.ConsumableTypes[_type] and SMODS.ConsumableTypes[_type].default and G.P_CENTERS[SMODS.ConsumableTypes[_type].default] then
            new_pool[#new_pool+1] = SMODS.ConsumableTypes[_type].default
        elseif _type == 'Tarot' or _type == 'Tarot_Planet' then new_pool[#new_pool + 1] = replacement_loteria
        elseif _type == 'Planet' then new_pool[#new_pool + 1] = replacement_zodiac
        elseif _type == 'Spectral' then _newpool[#_pool + 1] = 'c_ortalab_rooster'
        elseif _type == 'Joker' then new_pool[#new_pool + 1] = "j_ortalab_jester"
        elseif _type == 'Demo' then new_pool[#new_pool + 1] = "j_ortalab_jester"
        elseif _type == 'Voucher' then new_pool[#new_pool + 1] = "v_blank"
        elseif _type == 'Tag' then new_pool[#new_pool + 1] = "tag_ortalab_rewind"
        else new_pool[#new_pool + 1] = "j_ortalab_jester"
        end
        _pool = new_pool
        _pool_size = 1
    end
end
'''

## Patch SMODS get_pack
# [[patches]]
# [patches.pattern]
# target = '=[SMODS _ "src/overrides.lua"]'
# pattern = '''if add and not G.GAME.banned_keys[v.key] then cume = cume + (v.current_weight or 1); temp_in_pool[v.key] = true end'''
# position = 'before'
# match_indent = true
# payload = '''
# if v.kind ~= 'Buffoon' and v.kind ~= 'Standard' and G.GAME.modifiers.ortalab_only then
#     if not v.mod or v.mod.id ~= 'ortalab' then add = false end
# end
# '''